### PR TITLE
add the controlCrosshairImg option to GeotagPhoto

### PR DESCRIPTION
**Pull request by Abbe98**

### CODE REVIEW

**Comment by Abbe98** [comment]
poking @bertspaan

**Comment by bertspaan** [comment]
@Abbe98 Thanks for this PR! This raises an older problem: I'm no longer at the NYPL, and no one there I think will merge this PR. We should move this repo to a new location! I have a fork that we can use (https://github.com/bertspaan/Leaflet.GeotagPhoto), or we can find a different location. Do you have suggestions?

**Comment by Abbe98** [comment]
I think that's a okey location, but it would be nice if it wasn't a fork as forks aren't searchable etc.

**Comment by bertspaan** [comment]
I can reach out to someone at NYPL and see if they can move the repo to my account

**Comment by Abbe98** [comment]
@bertspaan that would be great, otherwise a git clone with a new remote would work to.

**Pull request merged**
